"""initial schema

Revision ID: 0fc6f5ad6d91
Revises: 
Create Date: 2026-03-22 14:04:20.597587
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fc6f5ad6d91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.String(length=10), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('categories',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_pdfs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('is_password_protected', sa.Boolean(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchants',
    sa.Column('name_normalized', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('default_category_id', sa.UUID(), nullable=True),
    sa.Column('merchant_type', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['default_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_normalized')
    )
    op.create_table('statements',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pdf_id', sa.UUID(), nullable=True),
    sa.Column('bank_name', sa.String(length=50), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('account_number_masked', sa.String(length=50), nullable=True),
    sa.Column('statement_period_start', sa.Date(), nullable=True),
    sa.Column('statement_period_end', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('min_amount_due', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_amount_due', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('available_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('closing_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('previous_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payments_received', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('parser_used', sa.String(length=100), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('parse_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pdf_id'], ['raw_pdfs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canonical_transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('merchant_raw', sa.Text(), nullable=False),
    sa.Column('merchant_normalized', sa.Text(), nullable=True),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('category_source', sa.String(length=10), nullable=False),
    sa.Column('account_masked', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=50), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('foreign_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('foreign_currency', sa.String(length=3), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('is_anomalous', sa.Boolean(), nullable=False),
    sa.Column('anomaly_reason', sa.Text(), nullable=True),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_patterns',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('pattern_type', sa.String(length=20), nullable=False),
    sa.Column('bank_hint', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parsed_transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('foreign_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('foreign_currency', sa.String(length=3), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('upi_id', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_method', sa.String(length=20), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_merchant_rules',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_sources',
    sa.Column('canonical_txn_id', sa.UUID(), nullable=False),
    sa.Column('parsed_txn_id', sa.UUID(), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('match_method', sa.String(length=30), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_txn_id'], ['canonical_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parsed_txn_id'], ['parsed_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_overrides',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('canonical_txn_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_txn_id'], ['canonical_transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_overrides')
    op.drop_table('transaction_sources')
    op.drop_table('user_merchant_rules')
    op.drop_table('parsed_transactions')
    op.drop_table('merchant_patterns')
    op.drop_table('canonical_transactions')
    op.drop_table('statements')
    op.drop_table('merchants')
    op.drop_table('raw_pdfs')
    op.drop_table('categories')
    op.drop_table('users')
    # ### end Alembic commands ###
