"""add insights tables

Revision ID: 70380c4c415c
Revises: dd80917cce50
Create Date: 2026-03-22 17:27:00.973648
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70380c4c415c'
down_revision: Union[str, None] = 'dd80917cce50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_summaries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('total_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_expense', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_flow', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('category_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_merchants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year_month', name='uq_monthly_summary_user_month')
    )
    op.create_table('budgets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('amount_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', 'period', name='uq_budget_user_category_period')
    )
    op.create_table('bills',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=50), nullable=False),
    sa.Column('account_masked', sa.String(length=50), nullable=True),
    sa.Column('statement_id', sa.UUID(), nullable=True),
    sa.Column('billing_period_start', sa.Date(), nullable=True),
    sa.Column('billing_period_end', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_due', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_patterns',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('description_pattern', sa.Text(), nullable=False),
    sa.Column('typical_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_variance', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('expected_day', sa.Integer(), nullable=False),
    sa.Column('last_seen_date', sa.Date(), nullable=False),
    sa.Column('next_expected', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurring_patterns')
    op.drop_table('bills')
    op.drop_table('budgets')
    op.drop_table('monthly_summaries')
    # ### end Alembic commands ###
