"""add raw_sms table

Revision ID: dd80917cce50
Revises: 0fc6f5ad6d91
Create Date: 2026-03-22 16:32:08.991745
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd80917cce50'
down_revision: Union[str, None] = '0fc6f5ad6d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_sms',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sms_hash', sa.String(length=64), nullable=False),
    sa.Column('sender_address', sa.String(length=255), nullable=False),
    sa.Column('sender_id', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sms_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=50), nullable=True),
    sa.Column('account_masked', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sms_hash', name='uq_raw_sms_user_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_sms')
    # ### end Alembic commands ###
